noun = input ("enter a noun:")
verb = input ("enter a verb:")
adjective = input ("enter an adjective:")
place = input ("enter a place:")
print ("take your", adjective, noun,"and", verb, "it at the", place)
